with open('numar.txt', 'r') as f:
    j=f.readline()
    a=int(j)

with open('inmultire.txt', 'w') as f: 
    f.write(str(a*1))
    f.write('     ')
    f.write(str(a*2))
    f.write('     ')
    f.write(str(a*3))
    f.write('    ')
    f.write(str(a*4))
    f.write('     ')
    f.write(str(a*5))
    f.write('     ')
    f.write(str(a*6))
    f.write('     ')
    f.write(str(a*7))
    f.write('     ')
    f.write(str(a*8))
    f.write('      ')
    f.write(str(a*9))
    f.write('      ')
    f.write(str(a*10))